config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "blogs#index"

  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :author_type, presence: true
  has_rich_text :content
end

app/models/test.rb
class Test < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find_by(id: params[:id])
  end

  def edit
    @blog = Blog.find_by(id: params[:id])
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to @blog, notice: "Added Blog"
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def update
    @blog = Blog.find_by(id: params[:id])
    if @blog.update(blog_params)
      redirect_to @blog, notice: "Updated Blog"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog = Blog.find_by(id: params[:id])
    @blog.destroy

    redirect_to root_path, status: 303, notice: "Deleted Blog"
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :author_type, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :author_type %>
    <%= form.select :author_type, ['User', 'Guest', 'Admin'] %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="error">
    <% if blog.errors.any? %>
      <h4>Validation Errors</h4>
      <ul>
        <% blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%= form.submit %>
<% end %>

app/views/blogs/edit.html.erb
<h2>Update Blog</h2>
<%= render "form", blog: @blog %>

app/views/blogs/index.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

<h1>Blog<h1>
<div class="blogs-container">
  <ul>
    <% @blogs.each do |blog| %>
      <li>
        <%= link_to blog.title, blog_path(blog.id)  %>
      </li>
    <% end %>
  </ul>
</div>


<%= button_to "Create Blog", new_blog_path, method: "get", class: "button" %>

app/views/blogs/new.html.erb
<h2>Create Blog</h2>
<%= render "form", blog: @blog %>

app/views/blogs/show.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

<h1>Viewing Blog</h1>

<div>
  <span class="show-head">Title: <span>
  <span class="show-value"><%= @blog&.title %><span>
</div>

<div>
  <span class="show-head">Author Type: <span>
  <span class="show-value"><%= @blog&.author_type %><span>
</div>

<div style="padding-bottom: 15px;">
  <span class="show-head">Body: <span>
  <span class="show-value"><%= @blog&.content %><span>
</div>

<div style="padding-bottom: 5px"><%= link_to "Edit Blog", edit_blog_path(@blog&.id), method: "get", class: "button" %></div>
<div style="padding-bottom: 5px"><%= link_to "Delete Blog", blog_path(@blog&.id), method: "delete", class: "button", data: { confirm: "Are you sure, you want to delete blog?" } %></div>
<div style="padding-bottom: 5px"><%= link_to "Back to Home", root_path, method: "get", class: "button" %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compose</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>